apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress
data:
  # property-like keys; each key maps to a simple value
                      # <pod>.<service>.<namespace>.svc.cluster.local
  WORDPRESS_DB_HOST: mysql-0.mysql.capstone.svc.cluster.local:3306
  WORDPRESS_DB_NAME: "wordpress"
